README.md
Adding new categories: Desktop Environments, Internet and Security. Slightly renaming other titles and general clean up as well.
=> Adding new categories

README.md
It's a nice file manager but not double nice :)
=> Double the Double Commander

README.md
Added a new popular code editor (Komodo Edit).
=> Added Komodo Edit code editor.

README.md
The "Weather" app is in reality "My Weather Indicator".
=> Fixed My Weather Indicator name

README.md
https://github.com/overtake/telegram is OS X version.
=> Fix telegram source link

README.md
- Changed the wording on the GNOME dictionary as it wasn't a complete sentence
- Added 0 AD to the games list.
=> Games and spelling edits

README.md
=> Add Yakuake drop-down terminal

README.md
- Chat Clients 
- Weechat - https://weechat.org/
- fast, light, modular command line IRC client 
- Development
- Sqlite Browser 
- ipython 
- Graphics - https://feh.finalrewind.org/
- Feh - https://feh.finalrewind.org/
- Very small and fast image viewer 
- Internet
- Midori - http://midori-browser.org/
- A lightweight free browser that runs well on low spec systems
- Productivity
- Zim 
- Command Line Utilities
- htop 
- wicd-curses
- Learn Linux
- Added linux pocket guide pdf 
- Moved existing office suites to office section 
- Added lyx 
- Added Gummi 
Moved 0 AD so they are in Alphabetical order 
Grammar and spelling 
fixed my username on the contributor list
=> created office section, added applications to sections, spelling fixes, and item reordering

README.md
Mình chỉnh lại phần DE và dẫn link thêm.
Thêm 1 số DE phổ biến: Pantheon (đẹp nhất trong các DE), Lxde (nhẹ nhất, cho máy cũ, yếu), LXQt (LXDE + Razor-qt), Budgie (mới nổi), GNOME Flashback (cho người thích hoài cổ Gnome 2).
=> Update Desktop Environment

README.md
Proposition to add my project Daily Reddit Wallpaper, originally made for Ubuntu.
=> Added Daily Reddit Wallpaper

README.md
/r/linux_gaming is a community of redditors who use GNU/Linux distributions to game
=> Add /r/linux_gaming to the subreddits list

README.md
GNU Typist is a free ncurses typing teacher
=> Add GNU Typist

README.md
Fixed issue #45 regarding `Rabbit VCS` missing the open source icon
=> Fix issue #45

README.md
WPS Office was erroneously marked as free/libre open source software, but it is a proprietary application developed by Kingsoft.
=> WPS Office is nonfree software

README.md
This video from Tek Linux shows various advanced Bash Shell commands in Linux for beginners.
=> added Tek Linux's Bash tutorial

README.md
Editors > Vim
`www.vim.org/download.php` > `http://www.vim.org/download.php`
=> Fixed Vim click the jump error

README.md
for not well formatted item in the list (as indicated to the contribution spec)
=> few adjustements

README.md
=> changed magneticnoodle to shuliandre

README.md
This project is amazing. All the software here... just amazing. Thank you all!
=> Added gThumb

README.md
Xcompmgr nhẹ hơn compton nhiều, dùng WM thường dùng Xcompmgr. Trước mình cũng dùng mà giờ bỏ luôn, khỏi cần hiệu ứng hay hình nền gì hết. :))
=> added Xcompmgr, edit link Compton

README.md
=> added indicator-sysmonitor

README.md
:) It would be better if there is a script that can sort those new items automaticly.
=> added alarm-clock, aria2, docky and cairo-dock.

README.md
=> Add new Item: Proxy

README.md, README_zh-CN.md, auto_sort/README.md, auto_sort/asort_zh.py
New items:
- Privoxy
- ProxyChains
New script `asort_zh.py` works for the file README_zh-CN.md, the Chinese version of this list.
=> Added new items & modified scripts

README.md
Added Rambox free and opensource cross platform software.
=> Added Rambox

README.md
Cmus is a powerful console based music player.. so it's worth this list...
=> Add cmus in audio category

README.md
Megasync
La capitaine icon theme
deja dup
Cutegram
Fish
Oh my fish
Fisherman
Terminix
Albert
Onlyoffice
Gnome Pomodoro
Also update the "last updated" date and add Ayo Isaiah to contributors
=> Add 11 new programs to the list

README.md
[AppImage](http://appimage.org/) - A format and tools to distribute Linux desktop applications to users of many distributions.
=> Add AppImage

README.md
Unity 8 Desktop
Macbuntu Transformation Pack
Anbox
38 Things To Do After Installing Ubuntu
Also update the "last updated" date and add Ogunjirin Emmanuel contributors
=> Added 38 things to do after installing ubuntu, andbox, unity 8,macbuntu

README.md
Added more IRC channels based on the which are the most popular found here: http://irc.netsplit.de/channels/?net=freenode
=> Add more IRC Channels

README.md
@LewisVo Hi, I just added a new item `goland`, and changed the link to the updated Chinese version of this list. I'll try my best to keep it up-to-date :). Thanks for your great work~
=> add goland, update the link to the updated Chinese version.

README.md
Claws was added in Email section
=> Claws was added in Email section

README.md
https://launchpad.net/kazam
Kazam is a simple screen recording program that will capture the content of your screen and record a video file that can be played by any video player that supports VP8/WebM video format.
=> Add kazam screen recording

README.md, README_zh-CN.md
Fixing readme ![ribbon](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg) link to point to https://awesome.re
=> Bugfix - Readme awesome ribbon link

README.md, README_zh-CN.md
Add 'red eclipse' to the games category
=> add 'red eclipse' to the games category

README.md
s-tui is a command line application to view your CPU frequency/temperature/utilization/power. It also uses stress to stress your CPU
=> Add s-tui to command line utilities

README.md
firehol.org tools for Linux
1. firehol
2. fireqos
3. iprange
4. update-ipsets
5. netdata
=> Added FireHOL and netdata tools

README.md
Added Qtile, a tiling window manager written in python.
=> Added Qtile to Tiling window managers

README.md
Include [Dino](https://github.com/dino/dino)
=> Add Dino in Chat clients

README.md
A FOSS to split, rotate, extract, mix and merge PDF files
=> Added PDFsam

README.md
=> Typo in freeware icon

README.md
LibreTime is a fork of Airtime that is actually updated and actively developed
=> Add LibreTime

README.md
Built on electron Api, this app can be used to stream audio, video torrents without downloading them fully.
https://webtorrent.io/desktop/
=> Added WebTorrent Desktop App.

README.md
Added `PHPStorm` IDE to `Development` Section
=> Added PHPStorm to Development Section

README.md
Vokoscreen is a free, multilingual and easy to use screencast recorder with audio for Linux. Features: detects webcams, avi and mkv video containers, mpeg4 and h.264 video codecs, adjustable frame rate, ...
=> Added Vokoscreen to Screen Recorders

README.md
adding : 
- Gramps
- Manokwari
- Ncdu
- MyCLI
- ikiwiki
and adding wiki software section
=> Adding gramps, manokwari, org mode, and some others

README.md
awesomewm's old url is not reachable anymore
=> correct url for awesomewm

README.md
Created Streaming subcategory inside Applications/Graphics
Added ReadyMedia (formerly known as MiniDLNA)
=> Added ReadyMedia and Streaming subcategory

README.md
Added categories to the "Games" list, re-ordered the old games.
I removed a few games which IMHO should no longer be on the list (unmaintained, Steam skin).
Let me know what you think.
=> Restructure the "Games" category

README.md
Added lots of more applications to the list, mostly the ones based on Electron.
=> Update README.md [Added Electron apps to the list]

README.md
=> Add Upterm

README.md
I add https://omnidb.org/en/ - a linux database tool
=> Add a database tool - omnidb

README.md
A few small fixes. +1 for your contribution and work. :)
=> Fixed some README copy

README.md
It's in my opinion a great project if you are a power user and want to search things quickly.
For example: 
```shell
xdg-open `fzf --preview 'coderay {}'`
```
=> Add fzf fuzzy finder

README.md
Wanted to find a good place to learn how to Git, so I chose a text file since this is easy enough. I've added four programs to the list that I've found very useful and think others may grow to love them also. :)
=> A few programs You may like:

README.md
Avocode is a native app (electron).
In Avocode you can inspect PSD and Sketch files, the properties of the elements, CSS code, etc. Awesome for frontend web development. A must have if you working environment is based on linux.
=> Added Avocode, awesome app for native PSD inspection in Linux #Hacktoberfest

README.md
Here are the changes again with the revisions added in.
=> More Grammar, More Programs 2:

README.md, README_pt-BR.md
Adding [this](https://github.com/sharkdp/fd) repo to command line utilities. I've add the portuguese-br translation as well.
=> Add FD to command line utilities

README.md, README_es-ES.md, README_pt-BR.md, auto_sort/README.md, auto_sort/asort_es-ES.py
Fixed more grammar on the English side while I was at it, but the Spanish translation is now complete.
The only remaining tasks will be to keep it up to date, and ask for the wider world to help with the Spanish in the list, since it's not my native language, and it has many technical terms I've not used much.
=> Spanish Translation finished ES

README_pt-BR.md
helping this issue: https://github.com/LewisVo/Awesome-Linux-Software/issues/196
=> Translate Android, C/C++ And Database sections to pt-BR and fix unicode errors

README.md, README_es-ES.md
Added YakYak - Google Hangouts client
Some simple Fixes in spanish translation.
=> added YakYak - Google Hangouts client #Hacktoberfest 

README.md
I added curseradio, raindbowstream, and translate-shell to command line utilities.
I also added polybar bar to desktop widgets but I'm not sure if it belongs there.
I also fixed some of the FOSS icons in the readme. I couldn't fix the wpgtk one somehow.
=> command line utilities, status bar, format fixing

README_es-ES.md
Multiple smaller grammar issues also have been corrected.
Also fixed wording in several places.
=> Markdown anchor tags updated es-ES

README.md
=> Added Nethack to games list.

README_pt-BR.md
=> finished section e-mail.

CONTRIBUTING.md
Just a quick put together of the different languages we currently have, and putting their "how to contribute" areas into one file. I figure it may be handy for growth. Unless having them in the list is the preference of the project?
I figure we can also go more in depth on how to contribute to Git in general here too, providing a decent tutorial that would help others in contributing here, but also elsewhere on Github, and with Git in general.
=> Creating a separate Contributions guideline:

README_pt-BR.md
=> Finished section "shell"

README.md, README_es-ES.md, README_pt-BR.md, README_th-TH.md
Adjusted Spanish to follow the new formatting, also as always smaller grammar was corrected in the English version where noticed.
Also additional software from English has been added to Spanish.
=> Moving Icons to the Left: README_es-ES

README.md, README_es-ES.md
Maintaining parity, also minor edits.
=> Adding Sonata to both README, and es-ES:

README.md, README_es-ES.md, README_pt-BR.md, README_th-TH.md
=> Changed Gogland to GoLand as it rightly should be.

README.md, README_es-ES.md, README_pt-BR.md, README_th-TH.md
Added Fedora to both README, and es-ES, added to pt-BR and th-TH to await translation since the translators haven't yet reached those points.
=> Added Fedora en-EN es-ES pt-BR th-TH

README.md
I've noticed that the list is missing a good desktop GTD (Getting Things Done) app for Linux, and I would like to suggest adding a tool I have build - [Everdo](https://everdo.net).
As a Linux user myself, I know that I would be delighted to find something like this. So I thought it might be a good fit for this list.
It's a productivity app focused on GTD methodology. It's looks good, has great UX and stores data privately on the user's computer (no cloud / SaaS dependency). Linux users might appreciate this. You can learn more about the app [here](https://everdo.net/blog/everdo-mission-values/).
Everdo is packaged for .deb, arch, appimage and rpm, so almost any Linux user can run it easily. It also works on Windows and Mac.
Here's a screenshot
=> Add Everdo app - cross-platform TODO/GTD app

README.md, README_es-ES.md, README_pt-BR.md, README_th-TH.md, README_zh-CN.md
Added Open Source icon and the link to the github page to the entry for Chat/All-in-one/Franz
=> Updated Franz entry

README.md
* removed uTorrent, it's not updated since 2015.05.15 https://www.utorrent.com/intl/it/downloads/linux
* added Tixati torrent client https://www.tixati.com/
=> Updated sharing files section

README.md
Removed OSS icon since it is proprietary
=> Updated Vivaldi

README.md
Added OSS icon with source link
=> Updated Darktable

README.md
Updated descritptions of 2 cli programs outside of command line section
=> Updated phockup and youtube-dl descriptions

README.md
Added Flameshot to the screenshot utilities. Because of my editor setup it also automatically removed whitespaces at the end of lines.
=> added flameshot

README.md
Please check
* alphabetically sorted
* added source for most games
* moved OpenRA to game engines since it require game assets, tried with red alert mod
* added openage to game engines
* added money icon for Minecraft
* fixed typo for itch
=> Updated Games section

README.md
=> Added Sound Switcher Indicator

README.md
Here is a short tutorial about what this software is intended for: https://www.youtube.com/watch?v=p2xrbmfqlV4
=> add DisplayCAL

README.md
https://hackr.io/tutorials/learn-linux-system-administration
=> Added Curated Linux Resources

README.md
Hello,
This adds [Movie Monad](https://lettier.github.io/movie-monad) ([source](https://github.com/lettier/movie-monad)) to the list.
- [Snap](https://snapcraft.io/movie-monad)
- [Flathub (Flatpak)](https://github.com/flathub/com.lettier.movie-monad)
- [AppImage](https://appimage.github.io/movie-monad/)
- [Arch](https://aur.archlinux.org/packages/movie-monad/)
- [OMG! Ubuntu! ](https://www.omgubuntu.co.uk/2017/12/movie-monad-simple-linux-video-player-haskell)
- [FOSSMint](https://www.fossmint.com/movie-monad-a-gtk-video-player-built-with-haskell/)
- [Ubuntuアプリのいいところ](https://ubuntuapps.blog.fc2.com/blog-entry-1015.html)
- [Blog do Edivaldo](http://www.edivaldobrito.com.br/player-movie-monad-no-linux/)
:+1:
=> Adds Movie Monad

README.md
added SSR into readme eng version, a new Screen Recorder option
=> SimpleScreenRecorder

README.md
=> update Mailspring, remove Nylas Mail

README.md
Unified SimpleScreenRecorder which was duplicated
Added FOSS icon with source link for:
* Audio recorder
* Arduino IDE
* Git
* Git Cola
* Wireshark
* Shutter
* OpenShot
* Pitivi
* Tor
* BleachBit
=> Added source links for several programs

README_fr-FR.md
=> Add Readme_fr-FR.md

README_fr-FR.md
🥖  Fix + Update translation in FR 🥖
=> Update readme fr

README.md, README_es-ES.md, README_fr-FR.md, README_pt-BR.md, README_th-TH.md, README_zh-CN.md
getting back into the swing of things.
Next section I'll probably put a pull request in for will be for Crypto mining.
The games reorg was to get the subcategories back into alphabetical ordering.
#338 #337 #312 
Putting in all the apps pertaining to these issues, so that they can also be closed.
=> Emulator Section + games Reorg + misc new apps:

README.md
This pull request contains moving entries only. There are no new software added or descriptions modified.
=> Cleanup Security and Utilities Section

README.md
Seems like there are duplicate categories in the `Games` section.
=> Cleanup games

README.md
[Tusk](https://github.com/klauscfhq/tusk) is a note taking on Linux. It has over 1500 stars on github as of 2018-08-05.
=> Add "Tusk" in the "Note Taking" section.

README.md
Quick and simple image processing at the command line.
=> added korkut

README_es-ES.md
Reviewed Spanish translation, fixed some Mayus mistakes, and typos. Added some translation for a know spanish word  Pre-note
=> Reviewed Spanish translation

README.md
Added taskbook https://github.com/klauscfhq/taskbook at `Time and Task` category. Amazing list, I really enjoy using it 😄
=> Add Taskbook

README_es-ES.md
Upgraded most of the README for spanish readers, still the list is not reviewed, mostly because of the linking.
#196
=> feat: Upgrades README_es-ES

README.md
=> Added FFmpeg to Video section

README.md
Sugar is a learning platform that reinvents how computers are used for education. Collaboration, reflection, and discovery are integrated directly into the user interface.
=> Sugar Desktop Environment

README.md, README_es-ES.md, README_fr-FR.md, README_pt-BR.md, README_th-TH.md, README_zh-CN.md
horst doesn't seem to update their repo anymore so there's a new upstream.
=> Update Arc Theme upstream URL

README.md, README_es-ES.md, README_fr-FR.md, README_pt-BR.md, README_th-TH.md, README_zh-CN.md
=> Update compton upstream URL

README.md, README_es-ES.md, README_fr-FR.md, README_pt-BR.md, README_th-TH.md, README_zh-CN.md
Cutegram has been discontinued.
=> Remove invalid link to Cutegram

README.md
It's not Linux software. See https://getsharex.com/docs/faq#will-sharex-be-released-on-linux-or-mac-operating-systems
=> Remove ShareX

README.md
which is a reading tool.
Polar is a personal knowledge repository for PDF and web content supporting incremental reading and document annotation.
=> add OSS software polar

README.md
Add bitwarden to Password Manager
=> Add bitwarden

README.md
https://github.com/bit-team/backintime/
=> Add Back In Time

README.md
[lemonbar](https://github.com/LemonBoy/bar) is a status bar similar to polybar, but far lighter and faster and much harder to set up.
=> Add lemonbar

README.md
=> Add MultiBootUSB

README.md, README_es-ES.md, README_fr-FR.md, README_pt-BR.md, README_th-TH.md, README_zh-CN.md
The links was wrong (AutoHotkey, for Windows) or old (Google Code). The fix was made for all languages.
In the contribution file there is not  a instruction to do a PR for each change. So each commit is a changed file.
[Here](https://github.com/autokey/autokey) the correct link.
=> Update AutoKey links

README.md
Add Synapse application in Local Search tools section.
=> Add Synapse

README.md
K2pdfopt optimizes PDF/DJVU files for mobile e-readers (e.g. the Kindle)
and smartphones. It works well on multi-column PDF/DJVU files and can
re-flow text even on scanned PDF files. It can also be used as a general
PDF copying/cropping/re-sizing/OCR-ing manipulation tool. It can
generate native or bitmapped PDF output, with an optional OCR layer.
=> Add K2pdfopt

README.md
Hey @luong-komorebi, I hope you are well.
Since I remember you liked the previous tool I developed, I very much hope you will like this one too. :)
=> Add Diskonaut

README.md
Added Viper4Linux, an audio effects processor based on Viper4Android
=> Added Viper4Linux - Audio effects

README.md
See issue [522](https://github.com/luong-komorebi/Awesome-Linux-Software/issues/522)
=> Changed Daily-Reddit-Wallpaper to active fork

README.md
Cross-platform Text Expander written in Rust
=> add espanso

README.md
Added cherrytree application in note taking section.
=> Added Cherrytree - Note taking

README.md
fix typo "encyrption" to "encryption"
=> Zerotier typo fix.

README.md
Hello :)
* added OSS icon + source link for Android studio (Apache2) and Code::Blocks (GPL3)
* added missing whitespace in Droidcam
* added empty line that caused rendering issue with the markdown editor/viewer I'm currently using: Marker (will will be a nice addition)
+ https://fabiocolacio.github.io/Marker/-
+ https://github.com/fabiocolacio/Marker
=> add 2 source links + fix typo

README.md
Added mortar, a tool to protect against system tampering.
=> Added Mortar - Boot Security

README.md
These (Wayfire and River) are the other two fastest growing Wayland Compositors, other than Sway that is already present.
=> Proposing the addition of two other Wayland Compositors

README.md
Hi @luong-komorebi - this is another app I originally created and spend most of my time maintaining. Since you liked my previous tools, I hope you like this one as well!
Good tidings to you.
=> Add Zellij

README.md
Add Wavebox to the browsers section
=> Add Wavebox

README.md
Blanket is GNOME application for white noise
=> Blanket added

README.md
MotoGT is a 2D bike racing game
=> MotoGT added

README.md
TuxType is for kids for familiarising with keyboard
=> TuxType added

README.md
Colotbot is an educational 3D games
=> Colobot added

README.md
**Audio**
- Spotify
**3rd Party Client**
- Chatterino
**All-in-one Client**
- Ferdium
**Official Client**
- Twake
**Data Backup and Recovery**
- Timeshift (_Add Linux Mint link_)
**Desktop Themes**
- Catppuccin
**Android**
- Waydroid
**Java**
- Eclipse (_FOSS Icon and link_)
**Machine Emulators**
- melonDS
**Graphic Creation**
- Pixelorama
**Compartmentalization**
- Distrobox
- Toolbx
**Other**
- Cryptomator
- VeraCrypt
**Other**
- BlueZ
- PipeWire
- Wayland
**Custom Linux Kernels (_New Category_)**
- GNU Linux-libre
- Linux-Hardened
- Liquorix
- XanMod
- Zen
**Reddit**
- AwesomeWM
- Cinnamon DE
- Kali Linux
- i3 Window Manager
- Linux4Noobs
- Linux From Scratch
- Linux Questions
- Qubes OS
- Red Hat
- Sway Window Manager
- Void Linux
- Xfce
Also include #560 and #507
=> Add new apps, update old links and fix typos

README.md
**Audio**
- Airtime (_Remove/Discontinued_)
- Auryo (_Remove/Discontinued_)
- G4Music
- Gnormalize (_Remove/Discontinued_)
- Lyricfier (_Remove/Discontinued_)
- Spicetify
- Spot
- Spotio (_Remove/Discontinued_)
- Spotube
- Tidal-hifi
**3rd party Client**
- NeoChat
- Tokodon
**E-Book Utilities**
- PDF Slicer
**Editors**
- CudaText
**Engine Re-creations (require the actual game)**
- NXEngine-evo (#445)
**Gaming Applications**
- Wine-tkg
- Wine-wayland
**Screenshot**
- Spectacle
**Streaming**
- Boatswain
**Web Service Client**
- GnomeTwitch (_Remove/Discontinued_)
- Streamlink Twitch GUI
**Compartmentalization**
- Pods
- VMware Workstation Player
**Sharing Files**
- AnyDesk
- Connections
**System Maintenance**
- AppImageLauncher
**VPN** (_New Category_)
- CyberGhost
- ExpressVPN
- IVPN
- …
=> Add new apps, remove old apps and fix outdated links/tags

README.md
I have tried to make some of the biggest categories (Audio, Games, Command Line Utilities) to smaller ones. This PR also includes new apps like : 
**IRC Client**
- Polari
**Data Backup and Recovery**
- Kopia
- Vorta
**Others**
- reFind
**Command Line Utilities**
- StreamLink
- WBOT #479
**Automation**
- XClicker
**Command Line**
- Pokete
**Machine Emulators**
- xemu
- RetroDeck
**Miscellaneous**
- Photoshop CCv19
- Photoshop-CC2022-Linux
**Password Manager**
- Authpass
=> Cleanup and add new apps

README.md, README_es-ES.md, README_fr-FR.md, README_pt-BR.md, README_th-TH.md
Replaced dead link https://github.com/oskusalerma/trelby with https://github.com/trelby/trelby
=> Fix dead link

README.md, README_es-ES.md, README_fr-FR.md, README_pt-BR.md, README_th-TH.md, README_zh-CN.md
Replaced dead link https://shadowsocks.org/en/index.html with https://shadowsocks.org/
=> Fix hyperlink

README.md, README_es-ES.md, README_fr-FR.md, README_pt-BR.md, README_th-TH.md, README_zh-CN.md
After some years in the works the new Arduino IDE 2.x have reached the stable release on September 2022
https://github.com/arduino/arduino-ide/releases/tag/2.0.0
The program have been rewritten and this is a new repository
=> Update Arduino IDE source link

README.md
Added
1. filelight
2. fkill
3. mitmproxy
4. portmaster
5. nmap
=> Add some software

README.md
added [cava](https://github.com/karlstav/cava) for audio visualizations,[tealdeer](https://dbrgn.github.io/tealdeer/) a cached tldr,[airpaste](https://github.com/mafintosh/airpaste) for terminal file sharing and [lolcat](https://github.com/busyloop/lolcat) to display colorful text and [nushell](https://www.nushell.sh/)
=> added few utilities

README.md
@DimitrisPa 
- [ccat](https://github.com/owenthereal/ccat)
- [mapscii](https://github.com/rastapasta/mapscii)
- [fast-cli](https://github.com/sindresorhus/fast-cli)
- [glow](https://github.com/charmbracelet/glow)
=> added some cli utilities

README.md, README_es-ES.md, README_fr-FR.md, README_pt-BR.md, README_th-TH.md, README_zh-CN.md
Adding Subtitld on all languages. Thanks!!
=> Added Subtitld

README.md
Adds [Strawberry Music Player](https://wiki.strawberrymusicplayer.org/wiki/FAQ); an active, mature fork of Clementine.
Strawberry is FOSS ([available on GitHub](https://github.com/strawberrymusicplayer/strawberry)), licensed under the terms of the GNU GPL-3.0 license.
=> Music Player: Add Strawberry Music Player

README.md
Adds [Open Surge](https://opensurge2d.org/); A 2D platformer and game creation engine inspired by the 16-bit Sonic the Hedgehog games.
Open Surge is FOSS ([available on GitHub](https://github.com/alemart/opensurge)), licensed under the terms of the GNU GPL-3.0 license.
=> Games/Miscellaneous: Add Open Surge

README.md
Adds JuK; a Jukebox application by KDE.
JuK is FOSS ([available on KDE Invent](https://invent.kde.org/multimedia/juk)), licensed under the terms of the GNU GPL-2.0 license.
=> Music Player: Add JuK

README.md
Added the following programs:
vhs
draw
gambit
slides
linuxwave
zramd
muffon
bauh
ytmdl
pulsar
navi
gpt4all
=> Add many programs

README.md
=> Remove i3-gaps
