README.md
I corrected the spelling of KeePass. 
Also noticed that the link pointed to KeePassX although the title was KeePass, so separated into an entry for each.
=> update info on KeePass/KeePassX

README.md
The Debian/Ubuntu repositories only have the abandonware version Nexuiz. Xonotic is a fork still under active development.
=> Added Xonotic to the list of games

README.md
Moved Kernel Newbies into its own section on kernel hacking specifically and expanded it to include a few other kernel programming resources.
=> Add a section on Linux kernel programming/hacking

README.md
The Ubuntu link under "Discussion Forums" in the ToC section didn't work as it linked to "#apple"
=> fixed Ubuntu anchor in Table of Contents

README.md
The beginner's guide has been removed from the wiki and it's not coming
back. You can read the relevant discussion here:
- https://www.reddit.com/r/archlinux/comments/4z7z0i/the_beginners_guide_has_been_removed_from_the_wiki/
- https://wiki.archlinux.org/index.php?title=Talk:Beginners%27_guide&oldid=443725#The_Great_Merge
- https://bbs.archlinux.org/viewtopic.php?id=216665
There are some archives of the beginner's guide but it's a bad idea to
link them since they'll become outdated as time passes.
Note: I didn't run `asort.py` since it made changes on other items as well.
=> Replace dead beginner's guide link for arch linux.

README.md
Added:
* Tilix is a gtk based terminal emulator and pretty awesome (:
* Nativefier creates a electron application from a website/web-app
Removed:
* Anatine is deprecated and unmaintained für 8 month now 
Ideas:
Maybe keep an eye out for [chirp](https://github.com/hanford/chirp), as it could be the "new Anatine" with a bit of time
=> added Tilix and Nativefier. Removed Anatine

auto_sort/asort.py, auto_sort/asort_zh.py
Without this change, the `end` and `file` parameters in print() cause problems in Python 2.  This approach makes print(x, end=" ") valid syntax in both Python 2 and Python 3.
=> from __future__ import print_function

README.md
exa is a modern replacement for ls. It uses colours for information by default, helping you distinguish between many types of files, such as whether you are the owner, or in the owning group. It also has extra features not present in the original ls, such as viewing the Git status for a directory, or recursing into directories with a tree view. exa is written in Rust, so it’s small, fast, and portable.(https://the.exa.website/)
=> added exa command line

README.md
Because, Lighttable is an open-source app.
=> Adding OSS Icon for Lighttable editor entry

README.md
Previous Pull request message:
> Thought that the Desktop Customization heading was a bit nebulous and broke it down into three sub categories. Also added two more programs I use on a daily basis, but forgot they weren't stock.
> 
> I'd imagine having many different branches and multiple maintainers would make this more difficult, but I'm enjoying myself helping here. Plus this list helped me a lot. I'm glad I'm able to give back in a way.
The Arc icon theme set also requires Moka to operate, since the list didn't have it, I added that as well.
=> Re-ordering Desktop Customization:

README.md
Move icons to the left as per #203 and re-check OS/free/paid software, update icons accordingly.
* Moved icons using regex find/replace in vim
* Changed some URLs to site pages rather than referrals
* Manually changed paid/non OS software icons
=> Move icons to left 

README_pt-BR.md
In the href `#outros` was some extra `]` on the end of all paragraphs. The href was fixed too, it was linking to the english href `others` that doesn't exists on this README
=> Fixed exibition of unexpected chars on the text on PT-BR README

README.md
Octave is a free Matlab replacement which is widely used in Universities and research institutes like CERN
=> Add GNU Octave in Education Category

README.md
`ddgr` is a Python3 utility to search DuckDuckGo from the terminal.
Features:
- Fast and clean (no ads, stray URLs or clutter), custom color                                                                                 
- Designed to deliver maximum readability at minimum space                                                                                     
- Specify the number of search results to show per page                                                                                        
- Navigate result pages from omniprompt, open URLs in browser                                                                                  
- Search and option completion scripts for Bash, Zsh and Fish                                                                                  
- …
=> Adding ddgr

README.md, README_es-ES.md, README_zh-CN.md, auto_sort/asort.py, auto_sort/asort_es-ES.py, auto_sort/asort_zh.py
I realize that asort.py script sort by the entire line content - in most of case by the GitHub URL instead by the project name. I just change improve this part.
- Fix README bad new line
- Do same fix for es-ES and zh-CN
- Apply sort on README.md, README_es.md and README_zh
- Don't run with pt_BR
=> Fix asort script to sort last terms in braces

README.md
[iTALC](https://github.com/iTALC/italc) is no longer maintained, but is succeeded by Veyon.
=> Removed iTALC, added Veyon

README.md
https://github.com/vladimiry/ElectronMail
Email
Unofficial desktop app for ProtonMail and Tutanota end-to-end encrypted email providers 
The app provides unique features that are not supported by the official in-browser web clients. Such as for example offline access to the email messages, full-text search (fully functional in offline), multiple accounts support, automatic login, and many more (see [readme](https://github.com/vladimiry/ElectronMail/blob/master/README.md) file for details).
=> add ElectronMail

README.md
https://github.com/minecraft-linux/mcpelauncher-manifest
https://mcpelauncher.readthedocs.io/en/latest/getting_started.html
The launcher itself is open source but the game, Minecraft: Bedrock Edition (cross-platform), is a paid application retrieved from Google's Play Store. That is why I used both icons.
=>  Added Minecraft: Bedrock Edition unofficial launcher

README.md
`what` is a terminal application I created to display network bandwidth utilization. Would be great if you'd like to add it. :)
=> Add "what" - a terminal bandwidth monitor

README.md
zoxide is a blazing fast autojump alternative written in Rust. It's orders of magnitude faster than other autojumpers, cross-shell, and extremely feature-rich.
=> Add zoxide under Command Line Utilities

README.md
Recently Riot has been rename to Element
https://element.io/blog/welcome-to-element/
https://itsfoss.com/riot-to-element/
=> Rename Riot to Element

README.md
cpupower-gui is a graphical program that is used to change the scaling frequency limits of the cpu, similar to cpupower.
=> Add cpupower-gui to System Monitoring

README.md
Allows for independent scaling of a window.
Context:
>  One of the aims here ended up being to have it work on a normal desktop, not just in a single-screen / single-activity like SteamOS did with steamcompmgr. The idea is that with Gamescope the game cannot interfere with your Linux desktop, while you also get more direct control over it for things like input, resolution, refresh rate and more. Griffais showed an example of Portal not working well with an Ultrawide monitor, and then when run with Gamescope at least the rendering was correct due to the sandboxing. Example below, launched as normal and then launched with Gamescope.
https://www.gamingonlinux.com/2020/09/valve-developer-shows-off-gamescope-for-linux-at-xdc-2020/page=2#r190150
=> Add Gamescope - the micro-compositor

README.md
Harmony did not receive any update since changing from FOOS to a Sublime Text like freeware/paid model, with last update coming almost 3 years ago (AUR package was updated to v0.9.1 on 2018-03)
=> Remove Harmony music player

README.md
The letter 'L' is capital in the official name of both the softwares.
=> Capitalize the letter 'L' in CLion and CodeLite

README.md
`mps-youtube` haven't been maintained for more than one year so i forked it and removed Youtube API. Now you can use `yewtube` to play youtube videos / playlists without having to add API_KEY. I have also added some features which were not present originally in `mps-youtube` like run _video as audio in VLC with no GUI._  
Edit:
- Now using `yewtube` you can download videos too (uses yt-dlp at backend).
=> added yewtube a fork of mps-youtube

README.md
Hi
I've suggested Standard Unix Notes - a GPG encrypted ntoes/notebook manager that runs in any Unix/BSD/Linux etc that supports GnuPG.
It is written in the Bourne shell avoiding Bash as that is not installed by default on some machines.
=> Added link to Standard Unix Notes - a GPG encrypted notes/notebook

README.md
Hi, I would love to see the excellent "IceWM" in the "stacking window managers" section.
It is a wonderful stacking window manager that can be used as standalone WM or that can be integrated with Gnome or KDE environments (for instance).
It is also the default WM for antiX Linux.
I use it daily as a standalone WM and I love it :)
https://github.com/ice-wm/icewm
https://ice-wm.org/
=> Add IceWM (stacking window manager)

README.md
Resource monitor that shows usage and stats for processor, memory, disks, network and processes.
Python port and continuation of bashtop.
=> Add bpytop

README.md, README_fr-FR.md, README_th-TH.md
The linked repository does not exist anymore: https://github.com/xmindltd/xmind
Could not find source code anywhere else...
The web page does not seem to link any source code.
=> Removed open source icon for xmind

README.md, README_es-ES.md, README_fr-FR.md, README_pt-BR.md, README_th-TH.md
Replaced dead/old link https://cgit.kde.org/trojita.git/ with https://github.com/KDE/trojita
=> Fix hyperlink

README_es-ES.md, README_fr-FR.md, README_pt-BR.md, README_th-TH.md, README_zh-CN.md
One of the GitHub links does not work anymore and there is a website now.
=> Fixe Gummi hyperlinks

README.md
* added money icon for Qoppa's PDF Studio, it is paid only in 2 tiers
* added money icon for Jetbrains GoLand, commercial with 30 days free trial
* added money icon for Jetbrains Webstorm, commercial with 30 days free trial
* added money icon for Jetbrains PHPStorm, commercial with 30 days free trial
* splitted IntelliJ IDEA between the open source and the proprietary commercial version, wording for feature taken from https://www.jetbrains.com/idea/download/#section=linux
* splitted PyCharm between the open source and the proprietary commercial version, wording for feature taken from https://www.jetbrains.com/pycharm/download/#section=linux
=> Commercial things

README.md
**Remove / Replace :**
- PulseEffects for Easy Effects _(This application was formerly known as PulseEffects, but it was renamed to Easy Effects after it started to use GTK4 and GStreamer usage was replaced by native PipeWire filters.)_
- Backgammon, Greed, Ninvaders, Tron _(No available links for the site or the source code)_
- RecApp for Kooha _(This project is archived, it's no longer under development. If you would like to continue development, please feel free to fork the project according to the GPL license.)_
- Whatever _(Electron app, last update Feb 10, 2017)_
- antimicro for AntiMicroX _(This repo is currently unmaintained. The code hasn't been updated for a while. There is new recommended version of this app called AntiMicroX)_
**Update links for :**
- GNOME Circle Apps
- Irssi …
=> Update site links & replace old apps

README.md
Adds [SC Controller](https://github.com/kozec/sc-controller); Allows for configuring and remapping Steam Controllers and others (without Steam Input).
SC Controller is FOSS ([available on GitHub](https://github.com/kozec/sc-controller)), licensed under the terms of the GNU GPL-2.0 license.
Note: The last release was in 2020, but it still sees fairly active development, and is a fairly mature project.
=> Gaming Applications/Tools: Add SC Controller

README.md
Adds [Okteta](https://apps.kde.org/okteta/); a hex editor by KDE.
Okteta is FOSS ([available on KDE Invent](https://invent.kde.org/utilities/okteta)), licensed under the terms of the GNU GPL-2.0 license or later. See the [LICENSES](https://invent.kde.org/utilities/okteta/-/tree/master/LICENSES) folder for more information.
=> Development/Supporting Tools: Add Okteta

README.md
Adds [Kasts](https://apps.kde.org/kasts/); a Podcast client for the Linux Desktop and mobile, and recently made part of KDE Gear as of KDE Gear 23.04.
Kasts is FOSS ([available on KDE Invent](https://invent.kde.org/multimedia/kasts)), licensed under the terms of the GNU GPL 2.0. Some components may be subject to different licenses but are compatible with GPL-2.0. See the project's [LICENSES](https://invent.kde.org/multimedia/kasts/-/tree/master/LICENSES) folder for more information.
=> Audio/Radio: Add Kasts

README.md
Adds [AudioTube](https://apps.kde.org/audiotube/); a YouTube Music client built with Kirigami, and recently made part of KDE Gear as of KDE Gear 23.04.
AudioTube is FOSS ([available on KDE Invent](https://invent.kde.org/multimedia/audiotube)), licensed under the terms of the GNU GPL 2.0. Some components may be subject to different licenses but are compatible with GPL-2.0. See the project's [LICENSES](https://invent.kde.org/multimedia/audiotube/-/tree/master/LICENSES) folder for more information.
=> Audio/Music Player: Add AudioTube

README.md
Adds [ProtonPlus](https://github.com/Vysp3r/ProtonPlus); a Wine and Proton tool manager for GNOME.
ProtonPlus is FOSS ([available on GitHub](https://github.com/Vysp3r/ProtonPlus)), licensed under the terms of the GNU GPL-3.0 license.
=> Gaming Applications/W.I.N.E.: Add ProtonPlus

README.md
Adds [Kron4ek Wine Builds](https://github.com/Kron4ek/Wine-Builds); provides various Wine build and build scripts. It gives easy access to prebuilt vanilla Wine binaries based on Wine and Wine-Staging, as well as builds of Proton based on Valve's Wine or with Valve's patches, but without other additions such as DXVK or vkd3d-proton. Some projects such as ProtonUp-Qt offer support for downloading these builds as well.
Kron4ek Wine build scripts are FOSS ([available on GitHub](https://github.com/Kron4ek/Wine-Builds)), licensed under the terms of the MIT license. However, Wine itself and some components used therein may be subject to different licensed; Wine, for example, is licenses under the [GNU LGPL-2.1 license](https://gitlab.winehq.org/wine/wine/-/blob/master/LICENSE).
=> Gaming Applications/W.I.N.E: Add Kron4ek Wine Builds

README.md
Adds [Winetricks](https://github.com/Winetricks/winetricks); an easy way to workaround problems with Wine from a GUI and command line, and acts as the basis for some other projects such as Protontricks.
Winetricks is FOSS ([available on GitHub](https://github.com/Winetricks/winetricks)), licensed under the terms of the GNU LGPL-2.1 license.
=> Gaming Applications/W.I.N.E: Add Winetricks

README.md
Adds [Linux Gaming Central](https://linuxgamingcentral.com) to the list of Linux news sites. Owned and operated by Mark Dougherty, previously an editor at Boiling Steam from 2015-2022, Linux Gaming Central primarily focuses on Linux gaming and Steam Deck news.
The website is FOSS ([yes, really!](https://github.com/linuxgamingcentral/website)) and takes a privacy-first approach to its analytical data by avoiding Google Analytics.
Note: One of my projects has been featured on Linux Gaming Central, but I am otherwise unaffiliated; just a reader.
=> Linux News: Add Linux Gaming Central

README.md
Adds [Warpinator](https://github.com/linuxmint/warpinator); A tool by Linux Mint for sharing files across LAN.
Warpinator is FOSS ([available on GitHub](https://github.com/linuxmint/warpinator)), licensed under the terms of the GNU GPL-3.0 license.
=> Sharing Files/File Sharing: Add Warpinator

README.md
Adds [ZeroBrane Studio](https://github.com/pkulchenko/ZeroBraneStudio); a powerful Lua IDE with modern development features.
ZeroBrane Studio is FOSS ([available on GitHub](https://github.com/pkulchenko/ZeroBraneStudio)), licensed under the terms of the MIT license. However, some of its components may be under different licenses. See the project's [LICENSE](https://github.com/pkulchenko/ZeroBraneStudio/blob/master/LICENSE) document for more information.
=> Editors/IDEs: Add ZeroBrane Studio

README.md
Adds [RubyMine](https://www.jetbrains.com/ruby/); a commercial and professional Ruby and Rails IDE by JetBrains available for Windows, macOS and Linux.
RubyMine is proprietary software and does not offer a Community Edition unlike other JetBrains products.
=> Development/Ruby: Add RubyMine

README.md
Adds [Konversation](https://konversation.kde.org/); A full-featured IRC client maintained by KDE.
Konversation is FOSS ([available on KDE Invent](https://invent.kde.org/network/konversation)), licensed under the GNU GPL-2.0 license.
=> Chat Clients/IRC Client: Add Konversation

README.md
Adds [KFloppy](https://apps.kde.org/kfloppy/); A graphical utility for the Linux Desktop to format floppy disks.
KFloppy is FOSS ([available on KDE Invent](https://invent.kde.org/utilities/kfloppy)), licensed under the terms of the GNU GPL-2.0 license.
=> Utilities/Disk Utilities: Add KFloppy

README.md
Adds [screenFetch](https://github.com/KittyKatt/screenFetch); a command-line utility for displaying Linux system information in a visually pleasing way. It has served as inspiration for other projects such as [neofetch](https://github.com/dylanaraps/neofetch).
screenFetch is FOSS ([available on GitHub](https://github.com/KittyKatt/screenFetch)), licensed under the terms of the GNU GPL-3.0 license.
=> System Info: Add screenFetch

README.md
Adds [lshw](http://lshw.ezix.org/); a command-line utility for listing hardware information on Linux.
lshw is FOSS ([available from ezIX](https://ezix.org/src/pkg/lshw)), licensed under the terms of the GNU GPL-2.0 license.
=> Command Line Utilities/Tools: Add lshw

README.md
Adds [Factorio](https://www.factorio.com/); a factory building sandbox that has seen significant development. As well as being available on Steam and GOG, it is available directly from Wube Software's website DRM-free. They also supply a Steam key upon purchase from the website. Game keys and a DRM free release is also available from Humble Bundle.
Factorio is proprietary, but treats Linux as a first-class platform. Linux performance has been known by the community to be stellar, and the developers even recently introduced stable, tested, native Wayland support. This was previously available with the used SDL version via an environment option, but had some issues. A recent release fixed remaining issues on Wayland and the game is now perfectly playable natively on Wayland. Not many games …
=> Games/Sandbox: Add Factorio
